#specify baseimage
FROM node:alpine

#set working directory
WORKDIR '/app'

#install dependencies
COPY package.json .
RUN npm install
COPY . .

#RUN npm install


#default command
#CMD ["npm", "run", "build"]
CMD ["npm", "run", "start"]

